api_version: 3
name: fl_nids

participants:
  - name: fedserver
    type: server
    org: uniandes
    fed_learn_port: 8002
    admin_port: 8003

  - name: internal
    type: client
    org: uniandes

  - name: it
    type: client
    org: uniandes

  - name: servers
    type: client
    org: uniandes

  - name: admin@nvidia.com
    type: admin
    org: nvidia
    role: project_admin

builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml

  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      config_folder: config
      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        overseer_exists: false
        args:
          sp_end_point: localhost:8002:8003
          heartbeat_interval: 6

  - path: nvflare.lighter.impl.cert.CertBuilder

  - path: nvflare.lighter.impl.signature.SignatureBuilder